### ISSUE TITLE
Update test scenarios for Calendar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/openpaas-gatling#15]
Users and events need to be provisioned first before running the performance tests. If you want to do some user provisioning but not having a tool yet, you can do it with the help of https://github.com/huy-ta/openpaas-provisioning.

#### To-dos

* [x]  Refactor event search test(s)
* [x]  Add Calendar CRUD tests
* [x]  Add Event CRUD tests (with no attendees)
* [x]  Add test cases for event CRUD with (lots of) attendees
* [x]  Add Calendar Mix Scenario
* [x]  Use Gatling simulations to provision events & calendars
* [x]  Stress the People API => Add this to the Create & Update Event scenarios
* [x]  Need to load static assets before doing anything
* [ ]  Add test cases for recurrent events
* [x]  The endpoints need to be changed once the web frontend makes direct requests to Sabre
* [x]  Integration with OIDC
* [x]  Instructions to run the performance tests (a.k.a. update README.md)

PRs:

- https://github.com/OpenPaaS-Suite/openpaas-gatling/pull/16

#### Definition of Done

For each of the problem above, make sure:

- The PR(s) are reviewed & merged to the `main` branch.
- The documentation is updated accordingly (README.md).
- The tests run without any problem in the `main` branch on the load testing platform with 1 user. Fix any problems that arise.
- The real tests are launched.

**Comment by huy-ta** [comment]
> The endpoints need to be changed once the web frontend makes direct requests to Sabre

@renaudboyer @MichaelBailly Do we have a plan to ditch the DAV proxy before UPN's deployment?

**Comment by renaudboyer** [comment]
It's in progress, the '/dav/api' prefix should be configurable although we may use the same path touted to Sabre
