### ISSUE TITLE
Update test scenarios for Contacts

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/openpaas-gatling#29]
Users and contacts need to be provisioned first before running the performance tests. If you want to do some user provisioning but not having a tool yet, you can do it with the help of https://github.com/huy-ta/openpaas-provisioning.

#### To-dos

* [x]  Provide a simulation to provision contacts
* [x]  Refactor the old tests
* [x]  Need to load static assets before doing anything
* [x]  Instructions to run the performance tests (a.k.a. update README.md)

PRs:

- https://github.com/OpenPaaS-Suite/openpaas-gatling/pull/30

#### Definition of Done

For each of the problem above, make sure:

- The PR(s) are reviewed & merged to the `main` branch.
- The documentation is updated accordingly (README.md).
- The tests run without any problem in the `main` branch on the load testing platform with 1 user. Fix any problems that arise.
- The real tests are launched.
